name = "strava-heatmap-proxy2-1"
main = "index.js"
# type = "webpack"

# Change this to your own account ID
account_id = "3bf936c72fa408abbac0791bb2be921e"

workers_dev = true
# route = ""
# zone_id = ""

compatibility_date = "2021-11-19"

# Controls how long Cloudflare should cache each tile before requesting again
# from Strava.
#
# Use "0" to disable caching.
vars = { TILE_CACHE_SECS = "86400" }

# [secrets, added in github and in CF]
# STRAVA_ID
# STRAVA_COOKIES
